routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::post('notifications', 'NotificationController@store');
//Route::post('push-notifications', 'NotificationController@sent');

Route::get('/home', 'HomeController@index');

Route::group(['namespace' => 'Auth'], function() {
//    Route::resources([
//        'message' => 'MessageController',
//    ]);
    
    Route::get('/admin', 'AdminController@index');
    
});

// Notifications
Route::post('notifications', 'NotificationController@store');
Route::get('notifications', 'NotificationController@index');
Route::patch('notifications/{id}/read', 'NotificationController@markAsRead');
Route::post('notifications/mark-all-read', 'NotificationController@markAllRead');
Route::post('notifications/{id}/dismiss', 'NotificationController@dismiss');

Route::group(['namespace' => 'Alert'], function() {
    Route::resources([
        'message' => 'MessageController',
    ]);
    
});

// Push Subscriptions
Route::post('subscriptions', 'PushSubscriptionController@update');
Route::post('subscriptions/delete', 'PushSubscriptionController@destroy');

// Manifest file (optional if VAPID is used)
Route::get('manifest.json', function () {
    return [
        'name' => config('app.name'),
        'gcm_sender_id' => config('webpush.gcm.sender_id')
    ];
});

resources/views/home.blade.php
@extends('layouts.app')

<meta name="csrf-token" content="{{ csrf_token() }}">

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard
                <a href="{{ route('message.create') }}" class="btn btn-info col-md-offset-2">Add new message</a>
                
                
                </div>
                


                <div class="panel-body text-center">
                    
                    <notifications-demo></notifications-demo>
                    
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    // CSRF for all ajax call
//      $.ajaxSetup({
//    beforeSend: function(xhr, type) {
//        if (!type.crossDomain) {
//            xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
//        }
//    },
//});
</script>

<script type="text/javascript">
  //  function sent(id) {
//        var person = {
//            name: $("#id-name").val(),
//            address:$("#id-address").val(),
//            phone:$("#id-phone").val()
//        }

       // $('#target').html('sending..');
       
       

//        $.ajax({
//            url: '/push-notifications/',
//            type: 'post',
//            dataType: 'json',
//            success: function (data) {
//                //$('#target').html(data.msg);
//                console.log(data);
//            }
//            //data: JSON.stringify(person)
//        });
//    }
</script>
@endsection